87 temp voice
skni-kod/PyChan-Bot pull request #124
Opened 2024-11-08 11:16 UTC by NimVrod

Wykonano #87 
Tworzenie kanałów na czas określony przez użytkownika (domyślnie 30 minut), kanał jest usuwany tylko wtedy gdy nie ma na nim żadnego użytkownika
Usuwanie tymczasowego kanału komendą
Sprawdzanie permisji do tworzenia kanałów

2024-12-05 15:46 UTC, Heryin commented on pychan/commands/utilities/tempVoice.py
> +            vc = await ctx.guild.create_voice_channel(name=f"Temp Voice Channel {datetime.datetime.now().strftime('%H:%m')}", category=ctx.channel.category)
`datetime.datetime.now().strftime('%H:%m')` Zwraca złą godzinę, zmień `.now()` na `.today()` oraz `%m` na `%M`

2024-12-05 15:46 UTC, Heryin requested changes
- Jakaś forma detekcji co godzinę czy istnieją tymczasowe kanały głosowe które są już po czasie, np. w przypadku restartu bota lub utraty połączenia z Discordem (uwaga na strefy czasowe, zmianę dat itp. https://docs.nextcord.dev/en/stable/ext/tasks/index.html
- Komunikat o ręcznym usunięciu kanału następuje dopiero po jego usunięciu, więc komunikat odnosi się do nieistniejącego kanału i skutkuje w `Usunięto #unknown`
- Ręczne usunięcie kanału nie usuwa istniejącego timera i po upływie czasu próbuje usunąć nieistniejący kanał z błędem 404
- Komunikat o usunięciu kanału po x czasu ma w formule `60*delete_after` zamiast po prostu `delete_after`, co skutkuje właściwym czasem usunięcia, ale ilością minut we wiadomości zwiększoną 60-krotnie
- Help do check_permission
- Może jakieś ograniczenie do np. 1 kanału na użytkownika, można dodać nazwę twórcy kanału na końcu jego nazwy

2024-12-07 12:04 UTC, NimVrod commented
- Dodano detekcję co godzinę aby usuwać kanały tymczasowy w przypadku restartu bota
- Naprawiano komunikat o usunięciu kanału
- Naprawiano błąd 404 w przypadku ręcznego usunięcia kanału
- Poprawiano komunikat o stworzeniu kanału
- Dodano help do check_permission
- Dodano limit 1 kanał tymczasowy dla użytkownika, używając słownika. Myślę, że bot nie będzie tak często restartowany aby był to problem, więc pominąłem dodawanie nazwy użytkownika do nazwy kanału

2025-04-15 20:03 UTC, Heryin approved these changes

2025-04-15 20:04 UTC, merged